name: Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-macos:
    name: "macOS"
    runs-on: macos-latest
    steps:
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: 16.0
      - uses: actions/checkout@v4
      - name: Build and Run Tests
        run: swift test

  build-linux:
    name: "Linux"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: SwiftyLab/setup-swift@latest
        with:
          swift-version: "6"
      - name: Build and Run Tests
        run: swift test
